### ISSUE TITLE
spec.address issue with grafana job

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/prometheus-boshrelease#97] opened 2017-07-25 07:44 UTC
When we deploy the prometheus without bosh power dns, the deployment is failing. The jobs' script is using the bosh hostname.
<spec.address> is used for the job scripts but without the powerdns it can't resolve the hostname. 
I think if we could choose whether we will use spec.address or spec.ip, it would be better.

**Comment by frodenas** [comment] 2017-07-26 20:08
What version of bosh are you using? Can you please provider me the output of `bosh status` (or `bosh -e <environment> env` if using bosh v2)?

If powerdns is turned off, `spec.address` [should return the IP address not the dns hostname](http://bosh.io/docs/jobs.html#properties). In fact, my tests are done on a bosh-lite without powerdns, and `spec.address` returns the ip address:

```
$ bosh -e lite env
Using environment 'https://192.168.50.4:25555' as client 'admin'

Name      Bosh Lite Director
UUID      63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79
Version   260.0.0 (00000000)
CPI       warden_cpi
Features  compiled_package_cache: enabled
          dns: disabled
          snapshots: disabled
User      admin

Succeeded
```

**Comment by marcus-sds** [comment] 2017-07-27 02:37
Hi, here is the bosh env command output.
Using environment '10.100.0.6' as client 'admin'

Name      bosh-test
UUID      e40fc09b-2695-42a0-a10a-3a7e57ac98c0
Version   262.3.0 (00000000)
CPI       aws_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      admin

**Comment by frodenas** [comment] 2017-07-30 02:34
Thanks @marcus-sds. I'll do some test next week to see if I can reproduce (and fix) this.

**Comment by frodenas** [comment] 2017-08-01 07:51
@marcus-sds Which jobs are failing? Which script is not resolving correctly the ip address? I just tested this on bosh `262.3.0` with dns disabled and is resolving the ip addresses not the hostnames.

**Comment by marcus-sds** [comment] 2017-08-01 08:30
Thanks @frodenas. 
The grafana's datasource script is shown like below.

GRAFANA_DATASOURCES_API="http://2c1ccf8c-6cf9-46f4-b484-485df3b1a357.grafana.prometheus1.prometheus.bosh:3000/api/datasources"
PROMETHEUS_URL="http://d7baca71-4484-4f8c-a6de-4f537c11e453.prometheus.prometheus1.prometheus.bosh:9090"

**Comment by frodenas** [comment] 2017-08-01 20:30
@marcus-sds I'm unable to reproduce this in my local environment using `262.3.0`. Are you by any chance using `dynamic` networks?

I've updated the release to use `ip` instead of `address` (https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/8d9e0961bc578ee0a20823ba01a6151f5f01d5de), but this only fixes the scripts using `spec`. When using `links`, there is no `ip` property. Do you mind creating a dev release from master and testing if it's solved?

**Comment by marcus-sds** [comment] 2017-08-02 00:26
@frodenas I'm using dynamic networks and I can try that and let you know.
Thanks.

**Comment by marcus-sds** [comment] 2017-08-02 02:59
@frodenas  I tested with static ips and found that spec.address is working. I think you can rollback the changes.
Thanks.

**Comment by frodenas** [comment] 2017-08-02 03:07
@marcus-sds Thanks for testing this. You should be hitting https://github.com/cloudfoundry/bosh/issues/1528.

**Closed by frodenas** 2017-08-02 03:07 UTC
Labels: bug

**Comment by marcus-sds** [comment] 2017-08-02 03:18
If we use dynamic network,  the deploy will fail,right?

On Aug 2, 2017 12:07 PM, "Ferran Rodenas" <notifications@github.com> wrote:

@marcus-sds <https://github.com/marcus-sds> Thanks for testing this. You
should be hitting cloudfoundry/bosh#1528
<https://github.com/cloudfoundry/bosh/issues/1528>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/97#issuecomment-319555213>,
or mute the thread

**Comment by frodenas** [comment] 2017-08-02 03:21
Exactly, the `spec.ip` references will work, but when using links, it will fail. There's nothing we can do in this bosh release to prevent this, as links don't have the `ip` property.
